fixing single quotations and apostrophs
rrthomas/hpmor pull request #95
Opened 2022-06-10 04:18 UTC by entorb

2022-06-13 13:09 UTC, rrthomas requested changes
Minor fixes needed!

2022-06-13 13:09 UTC, rrthomas commented on chapters/hpmor-chapter-000.tex
> +\item \textsc{Harry James Potter-Evans-Verres} grew up in a house filled to the brim with books. He once bit a math teacher who didn‘t know what a logarithm was. He’s read \emph{Gödel, Escher, Bach}
"didn‘t" is wrong.

2022-06-13 13:09 UTC, rrthomas commented on chapters/hpmor-chapter-000.tex
> +The opinions of characters in this story are not necessarily those of the author. What warm!Harry thinks is \emph{often} meant as a good pattern to follow, especially if Harry thinks about how he can
"wouldn’s" is wrong

2022-06-13 13:09 UTC, rrthomas commented on chapters/hpmor-chapter-000.tex
> +If you haven‘t visited \url{https://hpmor.com}, don’t forget to do that at some point; otherwise you'll miss out on the fan art, how to learn everything Harry knows, and more.
"haven‘t" is wrong

2022-06-13 13:09 UTC, rrthomas commented on chapters/hpmor-chapter-012.tex
> +ph‘nglui mglw’nafh J.~K.~Rowling wgah'nagl fhtagn
"ph‘nglui" is wrong

2022-06-13 13:33 UTC, entorb commented on chapters/hpmor-chapter-000.tex
> +\item \textsc{Harry James Potter-Evans-Verres} grew up in a house filled to the brim with books. He once bit a math teacher who didn‘t know what a logarithm was. He’s read \emph{Gödel, Escher, Bach}
fixed, thanks!

2022-06-13 13:36 UTC, entorb commented on chapters/hpmor-chapter-008.tex
> +One alert reviewer asked whether, if Luna is a seer, that means this is going to be an HPDM bottom!Draco mpreg fic. I regret that FFN does not allow me any larger font size in which to say NO. It hon
fixed, thanks

2022-06-13 13:37 UTC, entorb commented on chapters/hpmor-chapter-012.tex
> +ph‘nglui mglw’nafh J.~K.~Rowling wgah'nagl fhtagn
reverted

2022-06-13 13:38 UTC, entorb commented on chapters/hpmor-chapter-015.tex
> +I‘m sure I’ll find the time somewhere.
good catch!

2022-06-13 13:39 UTC, entorb commented on chapters/hpmor-chapter-018.tex
> +That does sound like the sort of thing I would do, doesn’s it?
fixed too, sorry for the mess!

2022-06-13 15:45 UTC, rrthomas approved these changes
This looks good! I think all the fixes are apostrophes, so the fix commit can be squashed into the main apostrophes one (also note English spelling "apostrophes" for the commit message).

2022-06-14 06:00 UTC, entorb commented
done

2022-06-16 08:43 UTC, merged